### ISSUE TITLE
TODO matubu

### ISSUE THREAD

**Issue by matubu** [louchebem06/ft_transcendence#11]
- [ ] modal wrong input error message
- [ ] pong duel
- [ ] improve sound
- [ ] fix desync score
- [ ] watch
- [ ] reduce lag
- [ ] add chat side navbar
- [ ] improve winner screen
- [ ] animation battle
- [ ] personalize game
